#!/usr/bin/env python2.7

import vpar
import pkt

dat_name = "/tmp/vdat"

vpar = vpar.VPar(dat_name)
pkt = pkt.Pkt(vpar)

# send a packet
num = 0
while True:
    ok = pkt.send("wow!");
    print "send",ok
    num += 1
    if not ok:
        break

vpar.close()

